services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pwordpress"]
      interval: 10s
      timeout: 5s
      retries: 10

  wordpress:
    image: ghcr.io/bdajoux/devsecops_grade:1.1.1
    container_name: wp_app
    restart: unless-stopped
    command: ["apache2-foreground"]
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('DISALLOW_FILE_EDIT', true);
        define('DISABLE_WP_CRON', true);
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:
